'use client';
import { useState, useCallback, useEffect } from 'react';
import { Header } from '@/components/Header';
import { Landing } from '@/components/Landing';
import { Results } from '@/components/Results';
import { useToast } from '@/components/Toast';
import { SAMPLE_DOC } from '@/lib/sampleDoc';
import type { AnalysisResult } from '@/lib/types';

export default function Page() {
  const [view, setView] = useState<'landing' | 'results'>('landing');
  const [level, setLevel] = useState<number>(() => {
    if (typeof window === 'undefined') return 2;
    return Number(localStorage.getItem('plainly_level')) || 2;
  });
  const [docText, setDocText] = useState('');
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [toast, toastNode] = useToast();

  useEffect(() => { localStorage.setItem('plainly_level', String(level)); }, [level]);

  const runAnalysis = useCallback(async (text: string, lv: number) => {
    setLoading(true); setError(''); setResult(null);
    try {
      const res = await fetch('/api/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, level: lv }),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Analysis failed');
      }
      const r: AnalysisResult = await res.json();
      if (!r.docType && !r.summary.length && !r.requires.length) {
        throw new Error('The analysis came back empty. Try again, or paste a clearer document.');
      }
      setResult(r);
    } catch (e: unknown) {
      // Fallback to sample breakdown if this is the built-in sample doc
      if (text.trim() === SAMPLE_DOC.text.trim()) {
        setResult(SAMPLE_DOC.breakdown);
        toast('Live AI was unavailable — showing the saved example');
      } else {
        const msg = e instanceof Error ? e.message : 'Something went wrong.';
        setError('Something went wrong translating that document. ' + msg);
      }
    } finally {
      setLoading(false);
    }
  }, [toast]);

  const onAnalyze = useCallback((text: string) => {
    setDocText(text);
    setView('results');
    runAnalysis(text, level);
  }, [level, runAnalysis]);

  const onBack = useCallback(() => {
    setView('landing'); setResult(null); setError(''); setDocText('');
  }, []);

  const onChangeLevel = useCallback((lv: number) => {
    setLevel(lv);
    if (docText && !loading) runAnalysis(docText, lv);
  }, [docText, loading, runAnalysis]);

  return (
    <div className="app-bg">
      <Header />
      {view === 'landing'
        ? <Landing onAnalyze={onAnalyze} level={level} setLevel={setLevel} busy={loading} />
        : <Results docText={docText} result={result} loading={loading} error={error}
            level={level} onChangeLevel={onChangeLevel} onBack={onBack}
            onRetry={() => runAnalysis(docText, level)} toast={toast} />}
      <footer className="site-footer">
        <div className="wrap">
          <p>
            <strong>Plainly</strong> is a plain-language helper, not a law firm, and using it does not create an attorney–client relationship.
            Explanations are generated by AI and may be incomplete or wrong. Nothing here is legal advice — for any decision affecting your rights,
            money, or safety, consult a licensed attorney. Documents are processed in your browser and are not stored.
          </p>
          <div className="spacer" />
        </div>
      </footer>
      {toastNode}
    </div>
  );
}
